Add an example for HKDF
mdn/dom-examples pull request #212
Opened 2023-03-22 20:11 UTC by wbamberg

See https://github.com/mdn/content/issues/25216.

This example is more or less a mashing together of the two existing examples, ECDH and PBKDF2.

We use ECDH to generate a shared secret, then HKDF to derive an AES encryption key from the shared secret.

I tried using `deriveKey` to get the HKDF key, rather than `deriveBits` followed by `importKey`. This worked fine on Chrome but not on Firefox, I don't know why.

2023-03-24 21:23 UTC, owlstead commented on web-crypto/derive-key/hkdf.js
In principle this is a nice example. I've got one nitpick: currently the IV is part of the fields of the instance. However, the IV should be communicated to the other party. This is a common mistake, and one that can lead to insecure code. Instead, the randomized IV should be prefixed to the ciphertext.

2023-03-25 05:35 UTC, wbamberg commented on web-crypto/derive-key/hkdf.js
Thanks! Of course we're not actually sending anything in this example, but perhaps instead of a global `ciphertext` here we could have a `message` object with `iv` and `ciphertext` members, which might help emphasise that these things should be sent together?

Does the same apply to `salt`?

2023-03-26 11:43 UTC, owlstead commented on web-crypto/derive-key/hkdf.js
It _could_ apply to salt. E.g. OpenSSL stores a salt when it derives a key from a password. It then derived _both the key and the IV_ from the salt - no need to randomize the ciphertext twice after all: the key / IV combination will only be used once if you do not reuse the salt.

OTOH, if you want to use the same derived key for multiple actions you'd probably have the salt stored somewhere else. HKDF actually works fine without a salt (i.e. empty salt) as well. For this example it makes sense to store the salt as well.

2023-04-10 02:18 UTC, owlstead requested changes
IV and salt need to be stored as indicated, hasn't happened so far as I can see (?)

2023-07-19 02:25 UTC, sideshowbarker commented
@wbamberg I’m doing some triage of open mdn/dom-examples PRs, and noticed that this one seems to waiting on a response from you.

2023-09-15 00:29 UTC, wbamberg commented
@sideshowbarker , @owlstead , I finally got around to updating this PR!

2023-09-16 16:21 UTC, sideshowbarker approved these changes

2023-09-16 16:21 UTC, merged